
version: 1.0.{build}
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: JsonNet.sln   	

artifacts:
  - path: bin\Net4.0\JsonNet.dll
